### PR TITLE
Fixing proxy JSON. Adding GDrive Upload.

### PR DESCRIPTION
**Pull request by kelnishi**
## Proposed changes
1) An additional integration for the Google Drive Upload endpoint
2) Fixing request body JSON data getting lost when calling through the proxy

## Types of changes

What types of changes does your code introduce to Pizzly?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/bearer/pizzly/blob/master/README.md#contributing-guide) guide
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by didroe** [comment]
Hi @kelnishi. Could you share some details about how you're making the request that fails to send the body please? 

I'd like to make sure that we don't need to do anything for other content types, and it would be better if we can find a solution that avoids buffering the body.

**Comment by kelnishi** [comment]
I'm using a siri shortcut from my phone that does the following:
1. POST to /proxy/goole-drive-upload/files?uploadType=media
- Request body is jpeg data. 
- The file is successfully uploaded to Google Drive, but it is in the root named "Untitled".
2. PATCH to /proxy/google-drive/files/<fileid>
- Content-Type=application/json
- Request body is `{"name":"something.jpg"}`
- This one fails to forward the JSON text over the proxy pipe and the file rename is unsuccessful.
- Logging inside the proxy (without bodyParser) shows `req.body` is undefined.

**Comment by didroe** [comment]
Sorry took me a while to find time to look at this.

I don't think there's any problem with Pizzly sending the body. `req.body` is set by `body-parser`, so it's expected to be undefined as we aren't using that.

The issue seems to be that the `Content-Type` header is missing as we only forward headers sent with a `Pizzly-Proxy-` prefix. I was able to succesfully rename a file using my phone by adding a header `Pizzly-Proxy-Content-Type=application/json` in the Siri shortcut. Give that a try and let me know if that works fo you.

**Comment by kelnishi** [comment]
Adding the header prefix fixes the issue for me. I'm also just now seeing this in the documentation. For people like me who don't read the docs, it would be nice if the proxy returned some kind of error instead of failing silently when receiving non-prefixed headers.

**Comment by didroe** [comment]
The reason we only support headers with a prefix is that you are rarely in full control of the headers that get sent. For example the HTTP client may add some (one common example would be `User-Agent`), or a tracing library might have hooked into the client to send information for tracking requests across mutliple services. 

If we made it an error to have non-prefixed headers then a lot of people would get that error with no way to fix it.

I think there is a good argument for forwarding headers that directly relate to the handling of the request, and that we know you will want to send, (eg. `Content-Type`) without needing the prefix.

**Comment by kelnishi** [comment]
Yep, makes sense. Figuring out how to fix my issue took a considerable amount of time. A simple warning log message would also have been useful and would've made diagnosis faster.

**Comment by didroe** [comment]
Thanks for the feedback, and for your time investigating this. Adding a log message sounds very useful. Perhaps we could add a "debug mode" that enables it, as it's likely to log something on every API call and that can be expensive (depending on where people are sending their logs). If that's something you would be interested in looking at, that would be great. Otherwise I will find some time to work on it over the coming weeks.

Regarding Google Drive Upload, please could you either drop the body handling changes from this PR, or open a new one with only the GDrive change?

**Comment by kelnishi** [comment]
Yep, here: [Adding Google Drive Upload Integration](https://github.com/Bearer/Pizzly/pull/211)

**Pull request closed without merging**
