### PR TITLE
Added Zendesk in integrations

### PR DESCRIPTION
**Pull request by k-guy-dev**
Added Zendesk OAuth in integrations.

### CODE REVIEW

**Review by Frenchcooc — CHANGES_REQUESTED** [review]
@k-guy-dev thanks a lot for your contribution! Can you update the `integrations/index.ts` file as well? Here's a great PR that you can look at https://github.com/Bearer/Pizzly/pull/157 to be sure everything is green.

**Comment by Frenchcooc** [comment]
Might worth having a look at https://github.com/Bearer/Pizzly/pull/161/files also. Looks like Zendesk Chat is already supported, so not sure how this differs?

**Comment by k-guy-dev** [comment]
> Might worth having a look at https://github.com/Bearer/Pizzly/pull/161/files also. Looks like Zendesk Chat is already supported, so not sure how this differs?

**Comment by k-guy-dev** [comment]
> Might worth having a look at https://github.com/Bearer/Pizzly/pull/161/files also. Looks like Zendesk Chat is already supported, so not sure how this differs?
I think they're the same. Sorry for this error.

**Comment by k-guy-dev** [comment]
@Frenchcooc Yup, just had a look at it, they're same, so there's no need for another one. Really sorry for this.

**Comment by cfabianski** [comment]
Ref: https://github.com/Bearer/Pizzly/pull/161

**Pull request closed without merging**
