### PR TITLE
feat: Automatically generates list of integrations

### LINKED ISSUE #138: Remove dependency on manual config imports
Dev experience enhancement:

Currently, each integration needs to be imported into the `index.ts` file in the integrations folder. Not a big deal, but it seems like something that could be done automatically at compilation time or when the server starts up by reading all the json files and changing the way integrations are added.

Thoughts? Any reason why this would be a bad idea that I'm overlooking? Might be a good first issue.

### PR DESCRIPTION
**Pull request by BjoernAkAManf**
Supports recursive directorys, which may allow future organization of APIs
into directories (e.g. google), if necessary.
Fixes #138

## Proposed changes

This improves the dev experience as outlined in the Issue #138. Further context can be found there.

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/bearer/pizzly/blob/master/README.md#contributing-guide) guide
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [X] Any dependent changes have been merged and published in downstream modules

Tests should not be necessary, due to the existing tests. If the generation wouldnt work, no integration would exist.
However if you'd like i could provide tests if necessary.

## Further comments
I didn't write the generation step in typescript, because that would make the integration within the Build Step needlessly complicated.

I hope this helps.

Happy Hacktoberfest.

### CODE REVIEW

**Comment by BjoernAkAManf** [comment]
I also merged it to the latest master right now, so it no longer conflicts 😄 .

**Comment by Frenchcooc** [comment]
Thanks a lot for your contribution! Looks very promising and it's indeed time-saver when adding new APIs ;) 

I'm wondering if handling nested API (e.g. `google/docs.json`) is a good thing. Today, Pizzly uses the configuration filename as a reference to the API (e.g. for `google-docs.json` all routes within Pizzly will use `google-docs`). How do you handle that with nested configurations?

**Comment by BjoernAkAManf** [comment]
I would argue that google-docs.json and google/docs.json would result in google-docs and google/docs respectively. However if that is desireable, a directory and a json file should not be allowed to share the same name, as that might result in ambiguity. Otherwise it would not be a problem right? I could also just remove the recursion as well and throw an error instead?

Open to suggestions on that, because i think it would be better for "scale" to be able to sort APIs accordingly, maybe even based on a canonical name (e.g. com/google/docs). Might make it easier to see if an api is contained within, if the numbers are above 200+ integrations.

**Comment by Frenchcooc** [comment]
@BjoernAkAManf I think its best for now to avoid nested integrations `google/docs.json` for now, otherwise the dashboard might need several updates to support this. 

It also introduces a breaking change if we move `google-docs.json` to `google/docs.json` which I'm keen to avoid.

I'm also wondering if triggering `node integrations/gen.js` at build time is the best. `yarn dev` won't be supported doing it like this.

@tanguyantoine might have a better idea on how to generate the integrations at a glance.

**Comment by BjoernAkAManf** [comment]
Alright. Then i'll rebase the PR and also add some errors for recursive occurances for now, so it'll fail. Regarding yarn dev wouldnt it be sufficient to run it within concurrently? I could rewrite it to watch for Changes if you'd like.

**Comment by BjoernAkAManf** [comment]
@Frenchcooc I added an error message and also another branch that adds the ability for the dev command to work.

By the way, it would be much appreciated, if you could add the hacktoberfest-accepted label before 1th Nov 😄.

**Comment by BjoernAkAManf** [comment]
It 'should' be ready for merge now actually. I made the generator work for build as well.

**Comment by Frenchcooc** [comment]
@BjoernAkAManf thanks again for your work and contribution!
Personally, I'm not keen to merge this for three reasons:
- the `integrations/index.ts` requirement seems not like a main blocker at this stage;
- you PR adds a new package to the project. Pizzly already has tons of packages. It's best to reduce that dependencies than increase it;
- there might be another / simpler way to manage the list of integrations with Typescript, but I'm not skilled enough for that.

@cfabianski might have another thought here. So I'm leaving this AS IS for now. Waiting for more inputs.

**Comment by cfabianski** [comment]
Thanks a lot for your contribution @BjoernAkAManf 
Like @Frenchcooc said, this is not a major blocker at the moment and it feels a little too complex to me. I'm closing this for now.

**Pull request closed without merging**
