### PR TITLE
Create spotify.json

### PR DESCRIPTION
**Pull request by Eteckq**
## Proposed changes

Adding spotify integration

### CODE REVIEW

**Review by Frenchcooc — APPROVED** [review]
@Eteckq thanks a lot for this PR 💯 If you are building something nice with Spotify, feel free to add it to the [Examples](https://github.com/Bearer/Pizzly/wiki/Examples) article within the Wiki.

**Comment by cliffdarling** [comment]
Should this also include an import statement in integrations/index.ts?  Or is there another way to have this integration available for use in the dashboard?

**Comment by Eteckq** [comment]
Ho yeah I've forgot it ! Ty !

Le sam. 19 sept. 2020 à 23:50, Cliff Darling <notifications@github.com> a
écrit :

**Comment by Frenchcooc** [comment]
Adding it ;)

**Pull request merged**
